[build]
  base = "frontend/"
  command = "REACT_APP_API_URL=https://retail-ai-backend.onrender.com npm run build"
  publish = "build/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://retail-ai-dashbord.onrender.com"